// Code generated by "stringer -type=Mode -output addressing.string.go"; DO NOT EDIT.

package addressing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IMP-0]
	_ = x[IMM-1]
	_ = x[ZPG-2]
	_ = x[ZPX-3]
	_ = x[ZPY-4]
	_ = x[INX-5]
	_ = x[INY-6]
	_ = x[ABS-7]
	_ = x[ABX-8]
	_ = x[ABY-9]
	_ = x[IND-10]
	_ = x[REL-11]
}

const _Mode_name = "IMPIMMZPGZPXZPYINXINYABSABXABYINDREL"

var _Mode_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
